version: '3'

services:
  reverse-proxy:
    image: traefik:v3.0
    command:
      - --api.insecure=true
      - --providers.docker
      - "--experimental.localPlugins.usersblocker.moduleName=github.com/ditkrg/traefik-users-blocker-plugin"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/plugins-local/src/github.com/ditkrg/traefik-users-blocker-plugin
